name: Deploy to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Azure CLI
      - name: Set up Azure CLI
        uses: azure/setup-azure-cli@v1

      # Add delay before starting the deployment to avoid SCM restart conflicts
      - name: Wait before deploying (30 seconds)
        run: sleep 30

      # Deploy to Azure App Service
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'al-food-coupon-techies'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ github.workspace }}/path-to-your-zip-file
